import bcrypt from 'bcryptjs';

export const getHashedPassword = (password: string) => {
  return bcrypt.hashSync(password, 10);
};

export const INITIAL_ADMINS = [
  {
    _id: 'admin-001',
    name: 'Sarah Jenkins',
    email: 'admin@leadpulse.com',
    password: getHashedPassword('Admin@123456'),
    role: 'admin',
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
    updatedAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    _id: 'admin-002',
    name: 'Alex Rivera',
    email: 'sales@leadpulse.com',
    password: getHashedPassword('Admin@123456'),
    role: 'admin',
    createdAt: new Date('2026-01-15T00:00:00Z').toISOString(),
    updatedAt: new Date('2026-01-15T00:00:00Z').toISOString(),
  }
];

// Helper to get past dates relative to current date (e.g. 2026-09-28)
const getDateDaysAgo = (daysAgo: number): string => {
  const d = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);
  return d.toISOString();
};

const getFutureDate = (daysAhead: number): string => {
  const d = new Date(Date.now() + daysAhead * 24 * 60 * 60 * 1000);
  return d.toISOString().split('T')[0];
};

export const INITIAL_LEADS = [
  {
    _id: 'lead-001',
    name: 'Ravi Kumar',
    email: 'ravi.kumar@abctech.io',
    phone: '+1 (555) 234-8901',
    company: 'ABC Technologies',
    service: 'Enterprise Cloud Migration',
    message: 'Looking for a dedicated cloud infrastructure team to migrate our legacy microservices to GCP and Kubernetes. Need proposal within 2 weeks.',
    source: 'Website Contact Form',
    status: 'New',
    priority: 'High',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
    followUpDate: getFutureDate(2),
  },
  {
    _id: 'lead-002',
    name: 'Elena Rostova',
    email: 'elena@novafinance.com',
    phone: '+1 (555) 345-9012',
    company: 'Nova Financial Group',
    service: 'Custom CRM & Analytics Suite',
    message: 'We are expanding our wealth management advisory arm and need a streamlined client tracking portal with custom role-based permissions.',
    source: 'Referral',
    status: 'Contacted',
    priority: 'High',
    lastContactedAt: getDateDaysAgo(2),
    createdAt: getDateDaysAgo(3),
    updatedAt: getDateDaysAgo(2),
    followUpDate: getFutureDate(3),
  },
  {
    _id: 'lead-003',
    name: 'Marcus Vance',
    email: 'marcus.vance@apexlogistics.net',
    phone: '+1 (555) 456-0123',
    company: 'Apex Freight & Logistics',
    service: 'Supply Chain Integration',
    message: 'Inquiring about API integrations with telematics hardware and custom inventory dashboards for 45 regional warehouse hubs.',
    source: 'Social Media',
    status: 'Converted',
    priority: 'Medium',
    lastContactedAt: getDateDaysAgo(8),
    createdAt: getDateDaysAgo(12),
    updatedAt: getDateDaysAgo(4),
    followUpDate: null,
  },
  {
    _id: 'lead-004',
    name: 'Dr. Priya Sharma',
    email: 'priya@zenithmedtech.org',
    phone: '+1 (555) 567-1234',
    company: 'Zenith MedTech Solutions',
    service: 'HIPAA Compliant Web Portal',
    message: 'Need a patient-doctor engagement system compliant with HIPAA and SOC-2 requirements. Budget is approved for Q4 rollout.',
    source: 'Website Contact Form',
    status: 'Contacted',
    priority: 'High',
    lastContactedAt: getDateDaysAgo(1),
    createdAt: getDateDaysAgo(4),
    updatedAt: getDateDaysAgo(1),
    followUpDate: getFutureDate(1),
  },
  {
    _id: 'lead-005',
    name: 'David Zhao',
    email: 'dzhao@luminarymedia.co',
    phone: '+1 (555) 678-2345',
    company: 'Luminary Digital Agency',
    service: 'White-Label SaaS Platform',
    message: 'We want to partner as a digital agency reseller for your CRM and marketing automation workflow platform. Can we schedule a partner call?',
    source: 'Advertisement',
    status: 'New',
    priority: 'Medium',
    createdAt: getDateDaysAgo(2),
    updatedAt: getDateDaysAgo(2),
    followUpDate: getFutureDate(4),
  },
  {
    _id: 'lead-006',
    name: 'Sophia Laurent',
    email: 'sophia@hauteatelier.fr',
    phone: '+33 1 42 68 55 00',
    company: 'Atelier Mode & Luxe',
    service: 'Omnichannel E-Commerce Suite',
    message: 'Seeking a bespoke clienteling and high-touch VIP customer service dashboard for our boutique flagships in Paris, Milan, and New York.',
    source: 'Website Contact Form',
    status: 'Converted',
    priority: 'High',
    lastContactedAt: getDateDaysAgo(6),
    createdAt: getDateDaysAgo(16),
    updatedAt: getDateDaysAgo(5),
    followUpDate: null,
  },
  {
    _id: 'lead-007',
    name: 'Carlos Mendez',
    email: 'carlos@solargrowth.io',
    phone: '+1 (555) 789-3456',
    company: 'SolarGrowth Residential',
    service: 'Lead Pipeline Automation',
    message: 'Generating 300+ inquiries weekly through ad campaigns. Need instant lead routing and SMS/email notifications for our field reps.',
    source: 'Advertisement',
    status: 'Contacted',
    priority: 'Medium',
    lastContactedAt: getDateDaysAgo(3),
    createdAt: getDateDaysAgo(7),
    updatedAt: getDateDaysAgo(3),
    followUpDate: getFutureDate(2),
  },
  {
    _id: 'lead-008',
    name: 'Amina Al-Mansoor',
    email: 'amina@gulfcapital.ae',
    phone: '+971 4 312 9000',
    company: 'Crescent Ventures',
    service: 'Enterprise Cloud Migration',
    message: 'Looking for tech audit and implementation partner for portfolio startups requiring secure API data pipelines.',
    source: 'Other',
    status: 'New',
    priority: 'Low',
    createdAt: getDateDaysAgo(5),
    updatedAt: getDateDaysAgo(5),
    followUpDate: null,
  },
  {
    _id: 'lead-009',
    name: 'Liam O’Connor',
    email: 'liam@dublinbiotech.ie',
    phone: '+353 1 496 0123',
    company: 'Emerald Bio Labs',
    service: 'Custom CRM & Analytics Suite',
    message: 'We require a lab sample tracking system integrated with a customer communication desk. Please send technical specifications.',
    source: 'Referral',
    status: 'Converted',
    priority: 'Medium',
    lastContactedAt: getDateDaysAgo(14),
    createdAt: getDateDaysAgo(22),
    updatedAt: getDateDaysAgo(10),
    followUpDate: null,
  },
  {
    _id: 'lead-010',
    name: 'Hannah Becker',
    email: 'hannah@urbanarchitecture.de',
    phone: '+49 30 2593 110',
    company: 'Bauhaus Modern Living',
    service: 'General Inquiry',
    message: 'Interested in seeing a live demo of your client relationship and contract management capabilities.',
    source: 'Website Contact Form',
    status: 'New',
    priority: 'Low',
    createdAt: getDateDaysAgo(0),
    updatedAt: getDateDaysAgo(0),
    followUpDate: getFutureDate(5),
  },
  {
    _id: 'lead-011',
    name: 'Kenji Sato',
    email: 'ksato@tokyosoftware.jp',
    phone: '+81 3 5555 0147',
    company: 'Nippon Systems Consulting',
    service: 'Enterprise Cloud Migration',
    message: 'Exploring multi-region failover and distributed relational databases for our client projects in APAC.',
    source: 'Website Contact Form',
    status: 'Contacted',
    priority: 'High',
    lastContactedAt: getDateDaysAgo(2),
    createdAt: getDateDaysAgo(9),
    updatedAt: getDateDaysAgo(2),
    followUpDate: getFutureDate(1),
  },
  {
    _id: 'lead-012',
    name: 'Chloe Bennett',
    email: 'chloe@beaconprop.com',
    phone: '+1 (555) 890-4567',
    company: 'Beacon Real Estate Trust',
    service: 'Lead Pipeline Automation',
    message: 'Managing commercial leases in Austin & Denver. Need a unified CRM to assign brokers to inquiries within 5 minutes.',
    source: 'Social Media',
    status: 'Converted',
    priority: 'High',
    lastContactedAt: getDateDaysAgo(12),
    createdAt: getDateDaysAgo(28),
    updatedAt: getDateDaysAgo(8),
    followUpDate: null,
  }
];

export const INITIAL_NOTES = [
  {
    _id: 'note-001',
    leadId: 'lead-001',
    content: 'Initial intake call reviewed. The engineering director wants a full statement of work by next Tuesday.',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
  },
  {
    _id: 'note-002',
    leadId: 'lead-002',
    content: 'Client requested NDA prior to sharing database schemas. Sent company standard mutual NDA.',
    createdBy: 'Alex Rivera',
    createdAt: getDateDaysAgo(2),
    updatedAt: getDateDaysAgo(2),
  },
  {
    _id: 'note-003',
    leadId: 'lead-003',
    content: 'Contract signed! Initial payment tranche cleared. Onboarding session set with integration engineering.',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(4),
    updatedAt: getDateDaysAgo(4),
  },
  {
    _id: 'note-004',
    leadId: 'lead-004',
    content: 'Discussed HIPAA BAA agreements. Compliance team approved standard security addendum.',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
  },
  {
    _id: 'note-005',
    leadId: 'lead-006',
    content: 'Enterprise agreement finalized for 3 global flagships. Tier 1 SLA package included.',
    createdBy: 'Alex Rivera',
    createdAt: getDateDaysAgo(5),
    updatedAt: getDateDaysAgo(5),
  },
  {
    _id: 'note-006',
    leadId: 'lead-007',
    content: 'Demoed live Zapier & webhook ingestion pipeline. They were impressed by 200ms lead routing speed.',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(3),
    updatedAt: getDateDaysAgo(3),
  }
];

export const INITIAL_FOLLOWUPS = [
  {
    _id: 'follow-001',
    leadId: 'lead-001',
    leadName: 'Ravi Kumar',
    date: getFutureDate(2),
    time: '02:00 PM',
    description: 'Send revised GCP cloud migration quote and architecture diagram.',
    priority: 'High',
    status: 'Pending',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
  },
  {
    _id: 'follow-002',
    leadId: 'lead-002',
    leadName: 'Elena Rostova',
    date: getFutureDate(3),
    time: '11:30 AM',
    description: 'Follow up on NDA signature and schedule technical demo with VP of Wealth Advisory.',
    priority: 'High',
    status: 'Pending',
    createdBy: 'Alex Rivera',
    createdAt: getDateDaysAgo(2),
    updatedAt: getDateDaysAgo(2),
  },
  {
    _id: 'follow-003',
    leadId: 'lead-004',
    leadName: 'Dr. Priya Sharma',
    date: getFutureDate(1),
    time: '04:00 PM',
    description: 'Review security questionnaire answers with Chief Compliance Officer.',
    priority: 'High',
    status: 'Pending',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(1),
    updatedAt: getDateDaysAgo(1),
  },
  {
    _id: 'follow-004',
    leadId: 'lead-007',
    leadName: 'Carlos Mendez',
    date: getFutureDate(2),
    time: '10:00 AM',
    description: 'Check in on field sales team approval of CRM mobile interface proposal.',
    priority: 'Medium',
    status: 'Pending',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(3),
    updatedAt: getDateDaysAgo(3),
  },
  {
    _id: 'follow-005',
    leadId: 'lead-005',
    leadName: 'David Zhao',
    date: getFutureDate(4),
    time: '01:30 PM',
    description: 'Provide agency reseller discount tiers & documentation.',
    priority: 'Medium',
    status: 'Pending',
    createdBy: 'Alex Rivera',
    createdAt: getDateDaysAgo(2),
    updatedAt: getDateDaysAgo(2),
  },
  {
    _id: 'follow-006',
    leadId: 'lead-003',
    leadName: 'Marcus Vance',
    date: getDateDaysAgo(3).split('T')[0],
    time: '09:00 AM',
    description: 'Introductory kickoff call with implementation leads.',
    priority: 'Medium',
    status: 'Completed',
    createdBy: 'Sarah Jenkins',
    createdAt: getDateDaysAgo(8),
    updatedAt: getDateDaysAgo(3),
  }
];
